### PR TITLE
Add new features to the bookingTextSender & a test App

### PR DESCRIPTION
**Pull request by zysjimmy**
New features: 
1. Allow one user to book multiple tours
2. Remind a customer if there's a time conflict with another tour

### CODE REVIEW

**Comment by Jekyll-SONG** [comment]
image
we need to remove the unique requirement in the database.

**Comment by Crysitna** [comment]
should it be getInfoQuestion("name");?

**Comment by zysjimmy** [comment]
@Jekyll-SONG You're right

**Comment by Crysitna** [comment]
@Jekyll-SONG sure, I'm working on it

**Comment by zysjimmy** [comment]
@Crysitna 
Because the chatbot will ask the date firstly and then the customer's name.

**Comment by QIYUANYUAN** [comment]
looks good

**Pull request merged**
